services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_HOST=project-db-cgi.smhrd.com
      - DATABASE_PORT=3307
      - DATABASE_USER=ohi0
      - DATABASE_PASSWORD=smart123!
      - DATABASE_NAME=ohi0
    networks:
      - mynetwork

  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # Flask 서버 포트 매핑
    volumes:
      - ./flask:/app  # flask 폴더를 컨테이너 내부 /app에 매핑
    networks:
      - mynetwork
    depends_on:
      - backend  # Flask가 백엔드와의 의존성

volumes:
  db_data:

networks:
  mynetwork:
